# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
      - name: Install mustache (to update the date)
        run:  apk add ruby && gem install mustache
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@target-branch
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: docker/
          destination-github-username: 'zapaishchykova'
          destination-repository-name: 'flywheel-docker'
          user-email: zapaishchykova@gmail.com
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: main-does-not-exist
          create-target-branch-if-needed: true
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
